apiVersion: v1
kind: Service
metadata:
  name: bonos-service
  labels:
    app: bonos-service
spec:
  type: ClusterIP # ¡Crucial! No debe ser LoadBalancer
  selector:
    app: bonos-service # Debe coincidir con el label del Deployment
  ports:
    - protocol: TCP
      port: 8004       # Puerto que usarán los otros servicios para llamar al servicio
      targetPort: 8004 # Puerto que escucha tu aplicación en el pod